const iconKeys = {
  chanceflurries: 'Snowing.svg',
  chancerain: 'Raining.svg',
  chancesleet: 'file-name.svg',
  chancesnow: 'Snowing.svg',
  chancetstorms: 'Thunder.svg',
  clear: 'Sun.svg',
  cloudy: 'Cloudy.svg',
  flurries: 'Snowing.svg',
  hazy: 'file-name.svg',
  fog: 'file-name.svg',
  mostlycloudy: 'Cloudy.svg',
  mostlysunny: 'Cloudy.svg',
  partlycloudy: 'Cloudy.svg',
  partlysunny: 'Sun.svg',
  rain: 'Raining.svg',
  sleet: 'file-name.svg',
  snow: 'Snowing.svg',
  sunny: 'Sun.svg',
  tstorms: 'Thunder.svg',
  nt_chanceflurries: 'Snowing.svg',
  nt_chancerain: 'Raining.svg',
  nt_chancesleet: 'file-name.svg',
  nt_chancesnow: 'Snowing.svg',
  nt_chancetstorms: 'Thunder.svg',
  nt_clear: 'Sun.svg',
  nt_cloudy: 'CloudyNight.svg',
  nt_flurries: 'Snowing.svg',
  nt_hazy: 'file-name.svg',
  nt_fog: 'file-name.svg',
  nt_mostlycloudy: 'Cloudy.svg',
  nt_mostlysunny: 'Sun.svg',
  nt_partlycloudy: 'Cloudy.svg',
  nt_partlysunny: 'Sun.svg',
  nt_rain: 'Raining.svg',
  nt_sleet: 'file-name.svg',
  nt_snow: 'Snowing.svg',
  nt_sunny: 'Sun.svg',
  nt_tstorms: 'Thunder.svg',
};

export default iconKeys;
