const iconKeysColor = {
  chanceflurries: 'snow-1.svg',
  chancerain: 'rain-3.svg',
  chancesleet: 'snow-1.svg',
  chancesnow: 'snow.svg',
  chancetstorms: 'storm-1.svg',
  clear: 'sun-1.svg',
  cloudy: 'clouds.svg',
  flurries: 'snow.svg',
  hazy: 'clouds-3.svg',
  fog: 'clouds-1.svg',
  mostlycloudy: 'cloudy-4.svg',
  mostlysunny: 'cloudy-4.svg',
  partlycloudy: 'cloudy-4.svg',
  partlysunny: 'sun-1.svg',
  rain: 'rain.svg',
  sleet: 'snow.svg',
  snow: 'snow.svg',
  sunny: 'sun-1.svg',
  tstorms: 'rain-2.svg',
  nt_chanceflurries: 'snow.svg',
  nt_chancerain: 'rain.svg',
  nt_chancesleet: 'snow.svg',
  nt_chancesnow: 'snow.svg',
  nt_chancetstorms: 'rain-2.svg',
  nt_clear: 'moon-2.svg',
  nt_cloudy: 'cloudy-1.svg',
  nt_flurries: 'snow.svg',
  nt_hazy: 'moon-1.svg',
  nt_fog: 'moon-1.svg',
  nt_mostlycloudy: 'cloudy-1.svg',
  nt_mostlysunny: 'moon-2.svg',
  nt_partlycloudy: 'cloud.svg',
  nt_partlysunny: 'cloud.svg',
  nt_rain: 'night-rain.svg',
  nt_sleet: 'night-rain.svg',
  nt_snow: 'night-snow.svg',
  nt_sunny: 'moon-2.svg',
  nt_tstorms: 'storms.svg',
};

export default iconKeysColor;
